### ISSUE TITLE
Save states ?

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#109]
Just wondered if you have any plans to add save state support (for ADF/IPF) ?

**Comment by sonninnos** [comment]
I certainly have plans, but it is holding the second place in my list. Right now I'm focusing on the first, which is CD32.

**Comment by MajorWilly** [comment]
Sounds good to me !

**Comment by sonninnos** [comment]
And since there has been at least some progress with CD32 (better be, since I've been at it for days), I'll tease a bit with these:

Getting the kickstart to boot wasn't that bad:
![retroarch_2019_09_06_01_47_14_425](https://user-images.githubusercontent.com/45124675/64490279-16a53880-d264-11e9-93a0-711bbf82ef09.png)

But getting a disc to detect was tricky and still is:
![retroarch_2019_09_07_22_56_45_662](https://user-images.githubusercontent.com/45124675/64490310-4b18f480-d264-11e9-989f-4cb69e0af625.png)

Also CD audio is not yet working but it is a start!
