### ISSUE TITLE
Having the ability to customize more controllers with the RetroPad settings in the Options menu

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#139]
I'm quite new to this emulator core; I've been an avid user of both WinUAE and FS-UAE till now.

In some games, I like to map custom keys from the Amiga keyboard itself to the Xbox One controller. One example is in the game Blues Brothers, where F7 is used to switch between both of the two players in 2 Player mode. I personally prefer to bind that key to the Y-button on my Xbox One gamepads (RetroPad X in the Options menu of this libretro core).

However, it seems like it's currently only possibly to do that for the Player 1 controller in the Options menu; I have not figured out to assign the Y-button of my secondary Xbox One controller to F7 as of now.

Could it be an idea to put custom mappings for a secondary gamepad as well in the Options menu? The menu could maybe be a bit on the "longer side" afterwards, but it would be nice for 2 player games on the Amiga let's say if you both want to assign the Start button as the P button (Pause in many games).

**Comment by sonninnos** [comment]
Since I don't think there is a case where both players would need their own complete set of extra RetroPad buttons, therefore making another mapping list mostly useless and inconvenient, how about a compromise:

I allow the same extra buttons to be pressed by the second controller, but all the rest is left to RA's game specific remappings, like preventing players from hitting each others keys or virtual keyboard by accident, reposition buttons etc.

As of now for example the only way of playing North & South in 2 player mode is to use the WHDLoad version with CD32 controllers, because both players need access to their own shift button on the keyboard. This simple change would allow that, and pretty much all other cases too.

**Comment by Gagert** [comment]
I think that would be a good compromise; I can only think of the games benefiting from a shared Pause/P button on the Start button of a gamepad itself (as of now), and as I mentioned I like to map the F7 button to both controllers in 2 player mode in Blues Brothers.

Otherwise, maybe some settings hidden in the options text file created for the specific game in the core itself (if there would be an oddball of a game needing that), thereby not bloating the Options menu in RetroArch even more? I can't think of any specific games that could use this "special" treatment however; more like a "what if".

**Comment by sonninnos** [comment]
Why should there be a mapping option for the fire button? 2nd fire (A) is mostly unused, therefore it is mappable.
