### ISSUE TITLE
Multiple mouses in the 2 player mode in Lemmings 1

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#140]
I'm not sure if this is anywhere near a highly featured request, but I'll put it here anyway.

I just did a test run with Lemmings 1 to see if the 2 player mode works for both players. Both my wired and my wireless mouse (for my HTPC setup) controlled the first player, and the right analog stick of the first Xbox One gamepad reacted only to player 1 during my short test.

Player 2 however seemed during my short test not possible to control anyway.

**Comment by sonninnos** [comment]
It will be confusing to do this, thanks to how the control ports are. Maybe the proper way is to create a new device type for mouse only use and leave this RetroPad web as it is.

And I'm not too sure if it even is worth the trouble, since you are not going to get very far in this game without a proper mouse. For something more slow paced like Settlers it could work, but even then..

**Comment by Gagert** [comment]
Thanks for the reply. Personally I prefer SNES Lemmings 1 in 2 player mode because that version is optimized for controllers, but I just wanted to throw this Issue in the Issue-tracker just to make sure this is known (this was some time ago also an issue in FS-UAE).
