### ISSUE TITLE
Flickering Team 17 logo in Alien Breed '92 and flickering Pinball Fantasies logo

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#141]
In the game Alien Breed Special Edition '92 at the very start, the Team 17 logo has some kind of "seizure" as it jumps up and down in a rapid speed, and no matter how I adjusted the various options in the libretro cores Option menu, I could not make the flickering of this high res logo go away. The same goes for the Pinball Fantasies logo that arrives just before the Table Selection Screen in Pinball Fantasies (also high res logo).

I'm not having those issues with either FS-UAE or WinUAE on Windows 10.

**Comment by sonninnos** [comment]
Interlaced modes are supposed to do that. You have enabled double scan on those other emus, and sure on still pictures it looks nice, but in movement not so much, because they drop the framerate in half.

Try comparing CELTIC-MultiscrollerScroller demo and you see what I mean.

And living with this feature is not so bad, because mostly it is only used in short logo screens.

**Comment by Gagert** [comment]
Thanks for the reply, I didn't know the technical reasoning behind those examples.

It's only nitpicking on my behalf; only shown during the startup in those games as far as I know.
