### ISSUE TITLE
Is Amiga CD32 support planned for this core (running iso/cue files)?

### ISSUE THREAD

**Issue by Gagert** [libretro/libretro-uae#145]
I've read through the Issue tracker here (both the closed ones and those that are open), and I've read through the readme-file on this github page for this libretro core. I didn't find any info regarding Amiga CD32 support, other than maybe CD32 support via whdload/hdf files.

Are there any plans for adding Amiga CD32 support in the future for this libretro core, and by that making it possible to run CD32 games through various CD-formats (iso/cue and so on)?

**Comment by sonninnos** [comment]
Yes there are.

**Comment by sonninnos** [comment]
I returned to take a jab at this again and here is some promising progress report:
- Regular ISOs and CUE/BINs without audio work fine
- CUE/BINs with audio do not work
- Figured out and fixed why A600 and A1200 stopped working after making CD32 to compile

![retroarch_2019_12_03_18_36_03_259](https://user-images.githubusercontent.com/45124675/70070612-97be6280-15fc-11ea-82ec-99ec34b46521.png)

![retroarch_2019_12_03_18_31_03_772](https://user-images.githubusercontent.com/45124675/70071136-832e9a00-15fd-11ea-9f52-f4634cfccaa5.png)


So almost there, finally!

**Comment by Gazdaman** [comment]
@sonninnos 
Great to see you are making progress with this.
Not sure if you are aware of a bounty I created? Link below
If you think some goals in it are achievable/un-achievable i'd be happy to hear your feedback?
It would be great to get this bounty claimed at some point!

https://www.bountysource.com/issues/58221940-bounty-amiga-cd32-core-with-support-for-2-player-gaming-support-for-android-as-a-minimum

**Comment by sonninnos** [comment]
Cheers! Everything else is already done except the CD audio.

I saw the bounty a while ago yes, but that is not why I'm having a go at this. It is just a learning exercise. But if I manage to claim it, it'll go to homeless cats. I'm rather surprised that there is no other helping hands and/or rivals in this pursuit..

**Comment by Gazdaman** [comment]
Awesome news mate. Good luck with the CD Audio.

**Comment by sonninnos** [comment]
Again some progress report to show I haven't given up yet, but nothing to brag about:
- CDA playing no longer crashes, and the CD LED will blink properly when playing, but no sound is coming through yet

The reason for this just not being a simple game of "connect the dots" is that the current source version does not have CDA playing functions at all, so I have had to convert newer c++ code to c, and I'm making it up and learning as I go along, since I'm not a professional.

**Comment by MajorWilly** [comment]
So it's fully working for games that don't use seperate Red Book audio tracks ?

**Comment by sonninnos** [comment]
Seems to be working well enough even if it uses CDA. Had a quick test of Super Stardust (uses CDA) and made it a few levels after this:
![retroarch_2019_12_16_15_12_19_796](https://user-images.githubusercontent.com/45124675/70910042-8e2ef480-2017-11ea-8b09-29b419babf3a.png)

![retroarch_2019_12_16_15_16_51_247](https://user-images.githubusercontent.com/45124675/70910052-9424d580-2017-11ea-8d0d-87e511db66b8.png)

I use only proper all-in-one images, and will not lift a finger to get MP3 audio tracks working, as MP3 decoding also only exists in c++ form and not included in these source files. But CHD support will be next in line once the audio works properly.

**Comment by MajorWilly** [comment]
Awesome work ! (I mentioned separate WAV, not MP3) :smile:

**Comment by sonninnos** [comment]
No it was nothing like that. CUEs work fine even with the files splitted.

**Comment by sonninnos** [comment]
@Gazdaman Up for some platform testing?

**Comment by MajorWilly** [comment]
I quickly tried a few games on Android if it's of any help -

Chaos Engine
Cannon Fodder
Beneath a Steel Sky
Banshee

They all worked fine. I also tried a CDTV game, Xenon 2. Also worked. Cheers.

**Comment by MajorWilly** [comment]
Although i've barely used this core recently (i'm currently still with the 8-bits), I did try a couple more games and they didn't work.

Super Skidmarks
Ultimate Super Skidmarks
AmigaJays 50 Game Disk

The Skidmarks games never get to gameplay, it just doesn't seem to do anything when it says it's loading the tracks etc. and sometimes when you click the menu buttons they don't respond. We had problems with these games before. I think only the original Skidmarks floppy version works. The WHDLoad one needed something like 16mb !
The AmigaJay 50 Game Compilation none of the games seem to load. Apparently they are the original CD32 files and not WHDLoad versions.

These issues are probably just down to general emulation accuracy (I tried Cycle Accurate). They worked fine on WinUAE. I've also heard that some games can benefit from FastRam (not sure).

Just a heads up, I noticed my WinUAE uses a single combined ROM file for CD32, instead of ROM+Extended ROM.

Lots of paragraphs ! Finally, do you have any love for the ZX Spectrum ? The FUSE core could benefit from a sprinkling of your magic. The FUSE version needs updating mostly. 

Merry Christmas !

**Comment by MajorWilly** [comment]
Although i've barely used this core recently (i'm currently still with the 8-bits), I did try a couple more games and they didn't work.

Super Skidmarks
Ultimate Super Skidmarks
AmigaJays 50 Game Disk

The Skidmarks games never get to gameplay, it just doesn't seem to do anything when it says it's loading the tracks etc. and sometimes when you click the menu buttons they don't respond. We had problems with Skidmarks before, oo-er. I think only the original Skidmarks floppy version works. The WHDLoad one needed something like 16mb !
The AmigaJay 50 Game Compilation none of the games seem to load. Apparently they are the original CD32 files and not WHDLoad versions.

These issues are probably just down to general emulation accuracy (I tried Cycle Accurate). They worked fine on WinUAE. I've also heard that some games can benefit from FastRam (not sure).

Just a heads up, I noticed my WinUAE uses a single combined ROM file for CD32, instead of ROM+Extended ROM.

Lots of paragraphs ! Finally, do you have any love for the ZX Spectrum ? The FUSE core could benefit from a sprinkling of your magic. The FUSE version needs updating mostly. 

Merry Christmas !

**Comment by sonninnos** [comment]
Super Skidmarks only goes to the game part with this core on the floppy version, and even then the "Select cars" menu will halt. HD install and WHDLoad, no difference, and will halt the same way always after loading the race data. Haven't bothered yet to find the exact cause, but it won't be trivial.

Also "Grand Prix Circuit" won't start with any version/setting. And "Executioner" WHDLoad version on A1200 only works **_without_** "Cycle-exact". Those are the only major defects I've found so far.

How does the combined ROM work, since WinUAE looks like this:
![winuae-rom](https://user-images.githubusercontent.com/4512467/71354588-14ea5100-2585-11ea-9046-752b9000b8ba.png)

Nope, never owned a Zedex. Cheerio!

**Comment by MajorWilly** [comment]
My WinUAE looks like this -

![CpWz_003](https://user-images.githubusercontent.com/52862903/71356162-45c48900-2579-11ea-9ea4-b30afc9ec4e1.png)

I must have some special ROMs.

**Comment by sonninnos** [comment]
Oh, didn't know there was such a thing. Better make it usable here too then.
