### ISSUE TITLE
Savestate oddity | Core Freeze (Certain Games, Certain Platforms ?)

### ISSUE THREAD

**Issue by MajorWilly** [libretro/libretro-uae#153]
I experienced a savestate that wouldn't load back correctly. I was playing James Pond 2, completed 4 levels, made a savestate. When I tried to load the state the next day, all I got was a black screen and about 1 second of sound (from the beginning of the game!) repeating over and over. Has the temp file been corrupted ?

I noticed that VICE now has a different approach to savestates (no temp files) and wonder if this method will be making it's way to PUAE ?

**Comment by sonninnos** [comment]
Temp files or not will not create or remove issues like this.

So far adf-based saves have worked as expected over here, but with hdf I've noticed some random irregularities, like mouse input skipping massively.

But whatever it is, it won't get fixed without changing/updating the UAE source code.

**Comment by rsn8887** [comment]
AFAIK save states with hdf have never been supported in any UAE, not even WinUAE. They seem to work most of the time but there's no guarantee.

**Comment by MajorWilly** [comment]
I forgot to mention, it was the ADF version I was using. Oh well, I guess it's hit'n'miss.

**Comment by rsn8887** [comment]
Hmm odd, because adf savestates should work.

**Comment by sonninnos** [comment]
Just had a random oddity with the ADF version of Cannon Fodder. Savestate was made at the menu screen were normal saves are made. All was fine to the point where the actual gameplay started, and after that the graphics were all corrupted and messed up (should've taken a screenshot for science). Loaded the same state again and no problems after that.

**Comment by MajorWilly** [comment]
Does that mean it's not loading (or saving) the memory back correctly on a regular basis ?

**Comment by MajorWilly** [comment]
There's definitely something weird. I tried on the PC. I haven't set up Retroarch properly since I re-installed Windows so this is a clean install of PUAE. For a quick test I loaded the ADF version of James Pond 2 (512+512 memory). Did a save state at the beginning of the game, moved him a bit then reloaded the state. I kept getting these flickering green things at the bottom of the sprite -

![James Pond 2 - Codename RoboCod-191016-105755](https://user-images.githubusercontent.com/52862903/66909414-a4fb9f80-f004-11e9-90fc-fb85b70a62fc.png)

Should I leave this issue open ?

**Comment by sonninnos** [comment]
This happening with the same standalone/other PUAE version would be the most interesting bit.

**Comment by sonninnos** [comment]
Also: Does it happen with IPF or a different cracked ADF? And on every "CPU compatibility" setting?

**Comment by MajorWilly** [comment]
It happens with both Cracked and IPF on 'Normal' and 'More Compatible'. It doesn't happen with 'Cycle Exact'. When using 'Normal' I never changed any settings between saving and loading. Note, this is the first and only game that i've tried using savestates so obviously other things may happen with different games (like you said with Cannon Fodder) and my first post above I couldn't even load the state back in. So savestates are unreliable unless you use Cycle Exact ?

**Comment by sonninnos** [comment]
Seems to depend purely on the game then, like the compatibility setting in general. I've used Normal on numerous games without problems.

On some instances the setting can be changed on-the-fly without problems and on some instances things would lock up until returning to the same intitial setting, and some times only reboot will cure the lock.

**Comment by MajorWilly** [comment]
Who's 'Shirley the Readme' ? :smiley:

**Comment by sonninnos** [comment]
Heh, She is a friend of Victor the Wiki, Roger the Repo and Clarence the Core.

**Comment by sonninnos** [comment]
I can't reproduce this problem with this game. All compatibility modes work the same.

**Comment by MajorWilly** [comment]
It's with the ECS version, ADF or IPF. It happens on Normal and Most Compatible but is OK on Cycle Exact. I can reproduce it every time. Maybe it's only noticeable at the very beginning of the game (outside in the snow). I was hoping that an obscure bug would surface as it's a bit weird that I couldn't load my savestate correctly at all (that I mentioned in the first post of this thread). Maybe it was just a one off.

**Comment by sonninnos** [comment]
I tried everything, switching the modes in realtime, restarting between and running around like a maniac. Also with the AGA version. No issues.. so maybe it is somehow performance related. What are your hardware specs? IPF I haven't tested yet, but I doubt it is any different.

Could you test also with WinUAE with the same settings?

**Comment by MajorWilly** [comment]
I still have the savestate of the first post issue if needed but I don't know if it would be of any use. I used the ECS Robocod version from Gamebase Amiga.

[James Pond 2 - Codename RoboCod savestate.zip](https://github.com/libretro/libretro-uae/files/3746725/James.Pond.2.-.Codename.RoboCod.savestate.zip)

**Comment by sonninnos** [comment]
That save does not work here either. What about this: 
[James Pond 2 - Codename Robocod.zip](https://github.com/libretro/libretro-uae/files/3746728/James.Pond.2.-.Codename.Robocod.zip)

**Comment by MajorWilly** [comment]
I couldn't reproduce it in WinUAE. You said you also had an issue with Cannon Fodder so is this just a random bug with savestates ?

**Comment by sonninnos** [comment]
The Cannon Fodder thing may be related also. Time will tell if it happens again.

**Comment by MajorWilly** [comment]
Just did a quick test and the phantom green pond glitch when saving doesn't happen anymore when the blitter options are disabled. I don't know if this is going to help savestates overall or not.

In WinUAE, 'Wait for blitter' is on by default unless you turn on Cycle Exact. Does that mean we are likely to get graphic glitches by leaving the blitter options off ?

**Comment by sonninnos** [comment]
Then something is fixed in later UAEs if the glitch does not happen with blitter waits. Perhaps the automatic handling is improved, since there is only one checkbox, and not three options (automatic, noidleonly, always) like here.

So far I've only encountered actual benefits from blitter waits if running A500 era games (Nebulus 2) with an A1200 setup.

**Comment by rsn8887** [comment]
FWIW, in UAE4ALL2 Switch/Vita, I made immediate blits the default because it worked better in my tests. Some games require waiting blits, for example Rock’n’Roll and Blastar. See here: https://github.com/rsn8887/uae4all2#games-with-known-fixes

**Comment by MajorWilly** [comment]
@rsn8887 I tried a few of those games on your list (Blastar, Mr & Mrs, Shufflepuck Cafe, PP Hammer & Spindizzy Worlds) and didn't have any issues with Both Blitter options OFF. I did see the flickering in Blastar if you use 68020, but 68000 works fine. I guess PUAE has much better accuracy than UAE4All2. 
I noticed IK+ on your list (no sound effects). This also happens on PUAE if you have 'More Compatible ON'. Turn it OFF and you get sound effects (also in Jimmy Whites Snooker, 'More Compatible' is Less Compatible! ).

**Comment by sonninnos** [comment]
I recently managed to get the mysterious black screen jam while trying out Rainbow Islands with CPU on "Normal". Saving and loading worked fine for a decent amount of time (2 worlds), but after a world change, the loading suddenly locked up and did not revive with more loading. But changing the CPU to "Cycle exact" fixed it right up.

So looks like the issue should be kept open. I'll try to search for differences in the savestate code between this and the latest WinUAE after I get some other issues sorted first. I wasted a lot of time on the never ending game of whack-a-mole CD32 again.

**Comment by MajorWilly** [comment]
I'm kinda glad someone else has experienced it which now makes it an actual thing and not just a one off. @rsn8887 will have to re-open this as it won't let me.

How is that CD32 thing going ? Is it still trial and error ?

**Comment by sonninnos** [comment]
Could you try if Monkey Island 2 locks up with "Cycle exact"? Hopefully you used the ingame saves. I haven't tested any hdf's or whdloads yet, because I'm trying to get the directory filesystem to work properly first. Non-whdload hd games work already, but not whdloads..

The Cannon Fodder issue I had is most likely related to fiddling with core options while the game was loading. Even though I only changed the turbofire core option (I have mouse buttons on LT+RT and turbofire on RT). The reason for suspicion is that once Turrican 2 also garbled out in normal state when only changing the turbofire core option.

And the reason for that is that all the options are updated even when there is no change, and maybe the CPU option just needs some simple logic to prevent it updating the UAE option unnecessary. VICE had the same kind of problems when changing any option while loading, because it also updated TDE option for no reason. Also the SID option always created a initialization crackle when for example only changing the VKBD theme.

There clearly is no trusting that the emulator can behave like nothing happens when a change is triggered with no changes.

And the CD32 always creates another problem when a problem is fixed. For example just enabling the necessary CFLAGS, it makes A1200 to crash. I haven't pinpointed the reason yet, but for now it looks like gayle chip emulation is to blame. For some reason A1200 works without it, even though it has it, but CD32 won't compile without it. And of course it is not enough to just update the gayle code from a later UAE version. CD emulation requires SCSI emulation, and so on and so on.. 

I've tried to approach it with a few different methods, like absolutely minimal changes and a related source updating from either PUAE 2.8.1b6 and/or latest WinUAE. I'm baffled that the PUAE documentation mentions CD32 like it should be working, but the code won't even compile without doing serious changes.

**Comment by MajorWilly** [comment]
I quickly skipped through Monkey Island 2 and got to Act 2 without any black screen freezes. I used the WHDLoad version, A600 profile, Cycle Exact ON and Blitters OFF. I'm not sure if that proves anything though ? It may have been luck that it didn't lock up :smile:

**Comment by sonninnos** [comment]
Sigh, not even "Cycle exact" is immune to this problem.. I had the same black screen jam with Turrican 2 after it started loading the next level, but that was fixed with switching to "Cycle exact", rebooting and reloading the savestate. Just as before, so that got me thinking that maybe "Cycle exact" should be the default.

But now with Fire & Ice (always at "Cycle exact") savestates worked fine for a long time, but suddenly in world 2 a save went kaput and ended up in guru meditation, and nothing helped to fix it.. It was not a black screen though, but just a still image lock-up and sound stopping with a sustained note.

**Comment by MajorWilly** [comment]
Oh, that's not good to hear. What's worse is that it seems to happen randomly so I imagine it's a pain in the arse for you to pinpoint the bug. It's a shame that there's no changelog or Git history you can check if anything related has been fixed in newer builds. GnoStiC's Github is gone so is this the latest version ?

**Comment by MajorWilly** [comment]
I had a random theory so I thought i'd try something. I loaded a game, Deliverance (ADF) and put the cheats on. I just played for a while. I started to get bored with the game but persevered and low and behold the game just froze. I was playing for about 30-35 minutes which is roughly the same time that I was playing Monkey Island 2 before the freeze happened. Could this be some sort of memory leak or just don't play an Amiga game for longer than 30 minutes ! Were you playing Turrican 2 for about this length of time ? I may try this again later.

**Comment by MajorWilly** [comment]
Yep, it happened again ! I loaded 'Donk', put infinite time on and just left it. After 30-35 minutes it froze.

**Comment by sonninnos** [comment]
With or without "Cycle exact"? I'm pretty sure I've played longer sessions than 30 min total, but maybe it starts over when loading a state.. Super Cars hasn't bugged once for instance, but I'll keep trying to hit that mark.

And indeed so far the only real game breaking problem has been in Fire & Ice even with "Cycle exact". All other issues have been on "Normal" and they recovered with "Cycle exact".

And with the same settings this does not happen with WinUAE? I've never actually used WinUAE on any other than "Cycle exact" (other than small test confirmations).

**Comment by MajorWilly** [comment]
It was with Cycle Exact OFF. I used A500 512+512. With my second test (Donk) I just started the game and left it running. I'll leave it running again with CE on.

**Comment by sonninnos** [comment]
And of course most useful would be to know if this happens with any other version of PUAE 2.6.1 and the latest 2.8.1b6.

**Comment by MajorWilly** [comment]
It didn't freeze with Cycle Exact ON. I left it for 50 minutes.

**Comment by sonninnos** [comment]
Damn. Better make it the default then. No idea if anything can be done with my pay grade.

**Comment by MajorWilly** [comment]
What platform did you experience your freezes on ? Mine were on Android but I tried a (completely) different game on PC Retroarch PUAE and it didn't freeze on Normal ? I'm getting a headache. If your freezes were on Android then that must be the culprit, if not, then it seems to be random-ish.

**Comment by sonninnos** [comment]
Windows action here only.

**Comment by MajorWilly** [comment]
Oh well. We'll just have to be wary of how long we play a single game for on Normal (40mins max) in case it locks up!

**Comment by MajorWilly** [comment]
I just tried 'Donk' on the PC Retroarch and it didn't freeze using the same settings. I give up!

**Comment by MajorWilly** [comment]
So I think this is happening only on certain games and certain platforms, maybe. The funny thing is, I tried 'Donk' again on Android as I know that it freezes after 35 minutes. I noted that the status bar was on and I got the freeze. I tried the game again, same settings but with the status bar off. It didn't freeze !?

**Comment by rsn8887** [comment]
Maybe there's a memory leak or something when status bar is on?

**Comment by MajorWilly** [comment]
May as well close this as well because it's too hard to reproduce and doesn't happen often enough anyway.
