### ISSUE TITLE
Error validating WHDLOAD 

### ISSUE THREAD

**Issue by DarishZone** [libretro/libretro-uae#230]
I got this error when running every Amiga 600 game: "Error validating WHDLoad - Block 4836 out of range".
I have 1200 and CD32 roms on other folders and those seems to run fine.
Files are .lha and was working fine before this error came out of nowhere.
I have some save state on A600 folder that i removed, i've also tried to replace .lha files on assumption that old ones could be corrupted, but the issue still persist.
Platform is Rpi.
Puae 2.6.1

Any clues?

**Comment by jamesgafys** [comment]
i reckon the whdload.hdf has somehow corrupted
u can get a free tool from aminet to fix this , but u will need a working WB to use it
easy way , uninstall core and then reinstall core

**Comment by DarishZone** [comment]
I resolved replacing whdload.hdf as you sugested, thank you!

**Comment by sonninnos** [comment]
Currently the easiest way is to simply delete the WHDLoad.hdf. A new one will be created automatically, and that problem should not appear with the latest version anymore.

It was the fault of the old HDF file using OFS filesystem instead of FFS. OFS seems to be very picky about shutting down cleanly and during read operations.

**Comment by DarishZone** [comment]
I have an old HDF indeed, makes totally sense.
Thank you very much.
