### ISSUE TITLE
[Request] Show selected disk name before closing tray (using hotkey)

### ISSUE THREAD

**Issue by WindyWinston** [libretro/libretro-uae#234]
Fairly recently @jdgleaver added the ability to see the name of the selected disk in a m3u when using the disk options in Retroarch. Is there anyway that it could be made to show the disk name in-game when using the hotkeys for changing disks ? For instance, if a game is 4 disks but it starts at disk 0, when the emulator asks you to insert disk 3 then it might be disk 4 that needs to be inserted. It's hard to explain. @sonninnos added this feature to lr-vice. Basically, when you eject the disk (using hotkeys) and cycle forward/back it shows the name of the diskfile selected before you finally 'close tray' (or whatever it's called these days). This is also useful because some games will crash if you insert the wrong disk.

I don't know if this would be best as a RetroArch thing so it would come up as a notification instead of saying just 'setting disk in tray 2/3' etc.? If it was then it may conflict with sonninnos' method in lr-vice.

**Comment by sonninnos** [comment]
Yes, I've planned to do the same kind of statusbar insert/eject notification like in VICE, but even there it only shows it after the action, so I don't think it'll help with inserting the wrong disk, unless you are fast enough to eject it before the game notices it.

If there is some other kind of widget notification thing then I haven't done it, since I don't use them.

**Comment by WindyWinston** [comment]
> but even there it only shows it after the action, so I don't think it'll help with inserting the wrong disk, unless you are fast enough to eject it before the game notices it.

Are you sure ? Vice only recognizes the disk after you press the 'disk eject toggle' hotkey. So when it asks me for a different disk I press the 'eject' hotkey then 'cycle next' which then shows me the disk name in the status bar, then press the 'eject toggle' hotkey again to insert it.

Maybe it would be better to see if @jdgleaver could add this to the Retroarch notification popup at the bottom of the screen where it normally says something like 'setting disk in tray 2/3' which is not very helpful :smile:  He added the disk names (taken from the m3u) in the 'Disk Control' menu but not in game when you use the hotkeys.

**Comment by sonninnos** [comment]
Yes I'm sure. Widget != statusbar. I just tried enabling widgets and that does show the disk name at the bottom when cycled. Statusbar (the one with the LEDs) shows the name only when inserted/ejected.

Of course that feature shall be added here too, as soon as the smoke clears with this sans libco update.

**Comment by WindyWinston** [comment]
In lr-vice I thought it was on the statusbar because I have zoom on but it's actually at the bottom of the screen. Something like 'Drive 8: 2/4: Elvira [Side 1].d64'. That's the one I'm talking about. It shows the disk name before inserting. As I say, I don't know if this would be better as a part of Retroarch because the disk change/eject notification appears in the same place as the widget. Hopefully jdgleaver is reading these posts.

**Comment by jdgleaver** [comment]
@WindyWinston Your request is definitely a frontend (RetroArch) thing, not specific to this core. Leave it with me - I shall add it to the TODO list  :)

**Comment by WindyWinston** [comment]
Thanks! Will this be a global thing for all cores that use a m3u playlist ? If so, it may conflict with @sonninnos ' widget thing in lr-vice ? (maybe cross the widget thing off your list sonninnos or you may both end up adding the same feature using different methods !). Thanks again guys.

**Comment by jdgleaver** [comment]
Yes, this would be a global thing for all cores - so the widget notification would just get a disk label addendum, like this: `Setting disk in tray: 1/6 [disk_label]`

I'm not familiar with the vice core - can its own notifications be toggled off?

**Comment by sonninnos** [comment]
Again, I did not do the widget thing in VICE. And the only way to toggle it off is to disable widgets completely.

And the placement is not that good now, since the animated balloon widget overlaps the disk name widget.

![retroarch_2020_02_02_16_18_48_020](https://user-images.githubusercontent.com/45124675/73609590-eaee6a80-45d7-11ea-8494-773390da0587.png)

**Comment by WindyWinston** [comment]
Yeah, that's what I mentioned above, they appear in the same place. Sorry @sonninnos I thought it was you that added that widget because it appeared roughly the same time as the status bar disk name. Who added it then ? :smile:

**Comment by sonninnos** [comment]
Darnation, looks like that message's position can't be changed core-wise, so at the moment the only option would be to pad it with empty space, which is not nice..

**Comment by WindyWinston** [comment]
Can it not be removed entirely (from lr-vice) ? It never used to be there ! Who was responsible ?

**Comment by sonninnos** [comment]
Sure it can be removed, but let's keep it until the balloon widget can show it.

But in the meantime I fixed the VICE statusbar to show the name also when cycled, and will push soonish after some more testing. Also added the padding, since it'll still be better than the overlap.

Looks like the message line has been in VICE since September.

**Comment by jdgleaver** [comment]
@WindyWinston These 2 PRs will allow the hotkey-generated notifications to display disk labels: https://github.com/libretro/RetroArch/pull/10096, https://github.com/libretro/RetroArch/pull/10097

While this will work for PUAE, it won't yet work for VICE - since the latter doesn't have support for the new disk control interface extensions (this is pretty easy to add though - I have some other stuff to do at the moment, but I'll try to get around to it later)

This doesn't change the position of the widgets - adjusting that will probably need some group discussion...

**Comment by WindyWinston** [comment]
Awesome ! Just what I wanted ! Looking forward to the update. Vice currently has a temporary Widget solution anyway.

**Comment by WindyWinston** [comment]
@jdgleaver I just updated Retroarch to the latest nightly on Android and now everything crashes when trying to run even when starting without content. I don't know if its anything to do with the notifications. Also, the Vice core gives constant loud white noise. Can you or anyone with Android confirm this ? I only have these two cores on my device so don't know if its a global thing.

**Comment by jdgleaver** [comment]
@WindyWinston Hmm... Well that certainly wouldn't be caused by my PRs...

Looking at recent commits, there have been a whole heap of clean-ups and stuff - and several things that might affect config files. I don't have an Android device on hand at the moment (I can test tomorrow), but in the meantime:

- Could you try running with a fresh config file? i.e. rename your existing config file, which should be in `storage/emulated/0/Android/data/com.retroarch/files/` (or similar)

- Could you post a log? Go to `Settings > Logging` and turn on `Logging Verbosity` and `Log To File`. Then restart RetroArch, and trigger a crash. The log file should be in `storage/emulated/0/RetroArch/logs`

**Comment by WindyWinston** [comment]
Yeah, I don't think it's anything to do with you 😄 . I reported it to Retroarch and aphextwin told me to report it on all the cores issues !!! What ? I did some tests and I think I narrowed it down to the opensl audio driver. He's now pushed a fix so i'll have to wait till tomorrow to test it. Sorry for tagging you on this !

**Comment by jdgleaver** [comment]
Ah, no worries - I'm just glad the issue got noticed, and it looks like we have a fix now, so hopefully all is well  :)

**Comment by WindyWinston** [comment]
His "fix" didn't work so looks like i'm stuck with it! Does this also happen on your Android device ?

**Comment by jdgleaver** [comment]
Ugh...

Yes, it's broken for me as well. I see you've given plenty of info in the issue thread - I think twinaphex should be able to narrow it down from that. Hopefully there will be a real fix soon!
