### ISSUE TITLE
Feature requests for parity with upstream projects

### ISSUE THREAD

**Issue by Shoegzer** [libretro/libretro-uae#246]
First, fantastic job with this core!  With all the nice improvements and changes lately, this has become my default Amiga emulator replacing upstream fs-uae.

Thought I would request a few features that would hopefully help to bring the core up to parity with upstream projects.  For easier tracking I thought I would include them together rather than as individual issue requests, though I can break them out if need be:

1. Support for creating HDF hard drive images.  fs-uae permits this via the fs-uae-launcher main menu.  Would be great if this core could do the same via the RA UI.

2. Support for expansion boards.  Again, fs-uae supports multiple expansion boards for accelerator (blizzard/cyberstorm), scsi, graphics (UAEGFX, Picasso II Zorro etc.), sound (toccata) and network (a2065) cards.  [Video Toaster](https://en.wikipedia.org/wiki/Video_Toaster) support would be a nice addition as well, even if not supported by fs-uae.

3. Support for saving content to floppies.  Haven't been able to confirm that this core *doesn't* permit saving but i haven't seen or read anywhere that it does either (and there's no core-specific wiki yet).  Ideally content would be saved via a change or diff file rather than writing over the original floppy itself, though the option could be available via toggle.

4. Internal inclusion of capsimg.  Note that fs-uae doesn't do this either but thought I would ask in case it's possible, in the interest of gaining some usability.

**Comment by i30817** [comment]
if you use a m3u you can create a save disk transparently, read the m3u section of the readme.

I don't think supporting image creation is anything but a over-reach myself, but a similar idea could be used i guess.

**Comment by Shoegzer** [comment]
Thanks, I'm aware of the m3u save disk option, but I was describing a process of writing any content to floppies, not just for game saves.  For example taking a blank formatted floppy image, writing a basic program and saving to it.  UAE upstream supports such features.  This would recognize the emulator as more than just a toy for playing games but also for educational/preservation purposes.

Image creation isn't part of core emulation of course, as the original Amiga could not do this inherently, so I'll agree that it's slight over-reach at least in that regard.  However it does make the emulated Amiga much easier to usewhen you want a quick way of formatting a hard drive and filling it with data.  This is why e.g. fs-uae supports it.

**Comment by i30817** [comment]
It's better to code a standalone application for that kind of stuff than to try to stuff it in a emulation, _especially_ on a retroarch core.

To be clear, retroarch already has a limited gui and is not a good fit at all for features that need much user GUI intervention. That's the reason why sonninnos is automating all that's possible to automate and make defaults and 'non-interactive' configuration possible (the filename strings configs)

Making a button in retroarch that will open a (native dependent) filechooser to produce a hdf is something that I'm confident will not happen, and would be a misdesign if it did.

**Comment by WindyWinston** [comment]
This core does save to floppies, they have to be unzipped ADF, but they alter the original file. It would be good to see it save a diff file of the changes instead of modifying the original. I think I read somewhere that @jdgleaver was thinking about implementing this feature. We could then have a option for write protect/enable.

**Comment by i30817** [comment]
Whdloads, and some hdfs don't save right? Because retroplay 'hd' games are distributed as _lha_ and i *never* saw a emulator modifying _that_ compressed format.

**Comment by Shoegzer** [comment]
@i30817 While I'll agree with you that RA has been viewed in the past as largely a vehicle for playing old console games, that certainly doesn't doom a given core to do nothing more than play games.  The fact that RA is evolving with Ozone and other more advanced and improved means of interfacing is a good reflection of this.  As a collective, RA is a great way to preserve old systems in the future as standalone apps tend to be maintained by single authors who tend to abandon their projects over time as RL issues inevitably find their way in; and so not preserving all the features of a given system would be a disservice.  

As I said, the "create an image" feature, while obviously not a feature of the Amiga, is more a convenience tool that would certainly be nice to see supported as it would boost usability.  Not everyone will use this core just to play games, some are serious Amiga users with experience with the actual systems, and so expanding this core's userbase with serious users can only be a good thing.  It's not like supported a few more Amiga features is going to cause any problems for casual users either.

You appear to speak with authority from the project.  Are you a developer of this core?  If not, I'd give sonninnos and/or twinaphex the courtesy of weighing in with their own thoughts on this.

@WindyWinston Hey thanks for the tip, that's good to know.  I had tested against one that didn't appear to save but I think it was just the original software not supporting it.  I also agree with you that a diff feature something along the lines of what mame does would be a great thing.

**Comment by jdgleaver** [comment]
Yes, I am indeed planning to add an optional floppy 'overlay' feature, which will transparently save to a new image in the save directory (i.e. original ADF files will be preserved without changes). No ETA yet, though - and I want to add support for memory-based save states first (I'll hopefully make a start on that one tomorrow...)

Oh and while I'm here:

> 4. Internal inclusion of capsimg. Note that fs-uae doesn't do this either but thought I would ask in case it's possible, in the interest of gaining some usability.

Unfortunately that's impossible, due to unresolvable licence conflicts - it's just not legal to include capsimg internally  :(

**Comment by Shoegzer** [comment]
@jdgleaver Fantastic!  Thank you for your efforts, that will be great to see whenever you have time to make it happen.  Just let me know if you need help testing anything when the time comes.

I hadn't realized capsimg inclusion ran afoul of licensing but what you say makes sense. If only there were a more license-compatible otpion available or in the works, or if capsimg itself changed licenses, though I suppose if either were that simple they would have already been done.

**Comment by sonninnos** [comment]
1. How about something like this:
   - A core option for a permanent hard drive, which would be included in all hard drive supported setups, and it would also change Automatic Model to A600 instead of A500 when launching floppies. Disabled of course when launching WHDLoad LHA stuff.
   - Because the biggest concern is the image size, which does not have a "one size fits all" option, it should be a directory filesystem under `saves`. But of course if something trivial like installing Workbench fails with it, then why not add a HDF option with a few sensible pre-defined sizes from 32MB to 512MB for example. Naturally the file would be created only if the file does not exist, even if the size changes in the core option.
   - This would allow using the core more like real hardware, as in boot into the HD installed OS anytime when resetting with the floppy ejected or starting without content.

2. Why, what is the benefit? I doubt this old 2.6.1 has such a wide array of options like current UAE versions, and frankly I have very little interest in anything with so little payoff that more than likely require more effort than just enabling a flag in the build options.

3. I guess a core option for forcing ADF floppies to read-only would also be warranted.

**Comment by Shoegzer** [comment]
Thanks for your helpful thoughts @sonninnos.
 
1. That sounds like a great idea, and I especially like the HDF option with selectable sizes.  I like your thoughts about using the core more like real hardware as I'll always be in favor of options that bring the core up to parity with what the actual systems could do. So for example the ability to specify/format a hard drive of even arbitrary size (as constrained by obvious tech limitations) would be ideal as such could be done on an actual system.

2. Actually I pulled that list of expansion boards directly from the upstream fs-uae UI.  I completely understand and appreciate your position if it's too much work but it would at least be nice to have it back-burnered for future consideration, in the spirit of being able to use the core as you would a real system.  I'm sure many UAE users (myself included) would love to ditch upstream solutions and just use your new core as it brings along many other RA benefits as well.

3. Agreed that would be a nice option especially if @jdgleaver's diff feature is implemented.  The way I'm imagining, this method could auto-toggle to read-only if diff is selected, so a core option something like:  `Floppy image writes: [Write to original | Read-only with diff]`

**Comment by sonninnos** [comment]
All right, bootable HD core option done and confirmed working with installing Workbench in both file and HDF modes. HDFs need formatting first and there is no need to hassle with partitions with either modes. And of course nothing prevents the user from replacing the created HDF file with their own, as it is only created if it does not exist.

I hope these HDF size options in MB are sufficient: 20, 40, 128, 256, 512

PR coming soon if all is fine.

**Comment by Shoegzer** [comment]
Excellent!  I compiled a new core after the PR merge, then stress-tested the feature and it seems to be working well.  Tested auto-creation of 20MB HDD with AmigaOS 3.1 workbench install, which worked flawlessly.  Then tried swapping out the HDD with a 512MB HDD image I had created years ago and the core recognized it just fine.  This is one heck of a great core especially as more upstream features llike this are added.  Thanks so much @sonninnos.  

A few issues/observations came up in testing, not necessarily related to the feature:

1. I noticed that when I change focus from PC to emulated keyboard (via scroll lock), F11 and F12 still perform RA core-specific functions e.g. display the OSK.  This is fine of course given the original Amiga keyboard only has 10 function keys (so those would never be seen by the system anyway), though I was surprised to see the core to take control.

2. Any chance you'd consider adding support for [libchdr](https://github.com/rtissera/libchdr) as other cores have done?  This would permit loading compressed CHD images, which would be nice for CD-based software such as CD32, and permit more people to test libretro-puae against those titles.

**Comment by jdgleaver** [comment]
> Any chance you'd consider adding support for libchdr as other cores have done? This would permit loading compressed CHD images, which would be nice for CD-based software such as CD32, and permit more people to test libretro-puae against those titles.

I've already dabbled with this a little, and it's quite a tricky proposition  :)

I do intend to revisit this, however - I use a lot of CD32 content, so it's quite an important feature for me. I'm currently bogged down in frontend (retroarch) work, but hope to get around to some more core stuff soon...

**Comment by Shoegzer** [comment]
@jdgleaver Thanks, that's great news.  I can help test anything you come up with.  I'll create a separate issue request for this so it can be tracked more easily (should have done that to begin with).

**Comment by Gagert** [comment]
Regarding saving to floppies (since it's mentioned here, so I don't have to start a new topic), I've encountered issues when it comes to saving my High Score in Pinball Fantasy, using the *.ipf version of the game with a *.m3u file to list the floppies for Course Disk One (Pinball Fantasies Disk 1 & Pinball Fantasies Course Disk 1 beneath inside the *.m3u file). I'm starting the game by using the *.m3u file with this libretro core.

Beforehand I used WinUAE to uncheck the "write protected" box on all the *.ipf-files for this game. After recently gaining my first High Score on Party Land (the first table), I wrote my initials and exited the board to make sure my High Score got saved. Then I was met with a black screen with a red box with red letters inside telling me something like "Please write enable Course Disk 1". That was very odd, because after quitting RetroArch and double checking if the *.ipf files within the Pinball Fantasies folder somehow still was write protected by using WinUAE for that operation, they still weren't write protected.

Can this libretro core at the moment write changes inside *.ipf-files?

**Comment by sonninnos** [comment]
AFAIK nothing can write to IPFs. The file modification dates always stay the same. Also trying to save hiscores in Giana Sisters IPF will result in a guru meditation.

What does that WinUAE write protection setting has to do with it? How and why would WinUAE settings protect any file while running some other software? And does the writing actually work with WinUAE then..?

**Comment by Gagert** [comment]
Thanks for the clarification; I thought that the WinUAE write protection setting could be a factor here (I thought that WinUAE could enable/disable write protection in the virtual floppies itself, thereby changing a value in the *.ipf files permanently for all other emulators to see).

It seems WHDLoad or ADF is the way to go then (the High Scores in the *.ipf version by the cracking team was insanely high, thereby I went with the *.ipf version).

**Comment by sonninnos** [comment]
That would be a great feature to have, sure. Or some kind of built-in diff mechanism for the changes and keeping the original file intact. But it only affects the way the image is accessed, if supported.

There might be a way to reset the hiscores. I remember back in the day I accidentally found a way to do it in Pinball Dreams, of course destroying my scores: Ejecting the second disk immediatelyish after first inserting it. 

Pinball Dreams WHDLoad version saves hiscores to a separate file, but Pinball Fantasies saves  them inside the disk images, ouch..

**Comment by Gagert** [comment]
There is supposedly a cheat to reset the Hight Scores, named vacuum cleaner or something like that. But the game gets buggy if I use the cracked version of Pinball Fantasies and enter this cheat (the crack-group probably didn't like it if anyone wiped their insane High Scores with that cheat, my theory). After entering that cheat, the game disables the Amiga keyboard, so that you cant Esc back to the main menu. That's why I went with the unaltered *.ipf version instead for that game.

**Comment by SultanOfDawn** [comment]
[welcom]() [add comment ]()
[#001]()

**Comment by sonninnos** [comment]
It seems these are as good as done.
