### ISSUE TITLE
Could you make a change to the 'whdload.prefs options' splash setting?

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-uae#258]
'splash delay' -1 to turn on the 'start' button when 'splash' is selected and disable the timeout (i assume 'config' will use the config file in /system as it is, and splash sets some defaults.

https://fs-uae.net/devel/docs/options/whdload-splash-delay.html

The thing is, 'splash' is already indicating you want to select a option, and the current time given is kind of unfriendly to select.

I also read you were supposed to be able to activate this menu on boot (like you can activate the readmes) but i wasn't able to, pressing enter and with a cd32 emulated pad (on a keyboard), which is the whole reason i changed to 'splash'.

Using the setting 'config' and editing the prefs file to set SplashDelay=-1 worked like i intended but i'd prefer that

1. the normal autoboot had a key that worked to start the config menu (not sure this is user error on my end or a conflict of 'amiga keyboard/native keyboard emulating a cd32 controller).
2. in splash mode or the 'autoboot interrupt' mode the menu appearing with that setting to -1 so people could chose the options leisurely not in 2 seconds and it's gone (couldn't do it in even 10 times).

**Comment by sonninnos** [comment]
'Config + Splash' already does that (both ConfigDelay and SplashDelay are -1), as in it shows the launch window and waits for a button press always. 'Config' (ConfigDelay=-1) alone won't do anything on some installs where there is no configs, hence the combined option for consistency.

The 'Splash' option is meant for just showing the window while waiting preload to finish, not for waiting any user input.

I haven't found any WHDLoad documentation on any button combination that would show the window on demand, where did you find it? Note that any FS-UAE specific stuff most likely will not apply, so looks like I have to script one from scratch.

**Comment by i30817** [comment]
> I haven't found any WHDLoad documentation on any button combination that would show the window on demand

I thought it was a feature here from these two lines in the readme:

> Hold fire button at boot for launch selector
> Hold spacebar at boot to show ReadMe and start MkCustom

Apparently launch selector isn't what i thought. Is it that filechooser that appears on non-whdload hds with .info file?

**Comment by i30817** [comment]
Also just to be clear, from the name i thought 'config' was a option to read the config file in /system and not change anything there (unlike the others that change settings). This is correct yes?

**Comment by rsn8887** [comment]
@i30817 is your issue resolved with sonninos' explanation above? If you still have an issue, please comment and state clearly what it is. If not, please close this issue here in github to keep everything tidy, thanks!

**Comment by sonninnos** [comment]
> this feels somewhat redundant then.

I included the splash-only option because WHDLoad does that by default, and some might like it instead of this core default of nothing.

> I thought it was a feature here from these two lines in the readme:

Closely related but ultimately unrelated feature at the moment, but sure, could be expanded to force the splashconfig on demand also.

> Apparently launch selector isn't what i thought. Is it that filechooser that appears on non-whdload hds with .info file?

Does not matter if it is WHDLoad or not, it just offers the .info selection if there are any.

> Also just to be clear, from the name i thought 'config' was a option to read the config file in /system and not change anything there (unlike the others that change settings). This is correct yes? Or if it changes anything it's just the 'config delay'.

No. `WHDLoad.prefs` is always read from `system`, even if the option is disabled. Disabled just forces the delay options to be the core default ones as in none. 'Config' changes ConfigDelay to -1, 'Splash' changes SplashDelay to 150, 'Config + Splash' changes both to -1.

Sure, maybe not the best method available, but that is the one I settled with.

And I thought the core option sublabel is pretty clear about it:
"'Config' shows the config screen only if the slave supports it. 'Splash' shows the splash screen always."

**Comment by i30817** [comment]
It's not clear that the right option to delay until confirmation is 'config+splash' because the sublabel  in retroarch doesn't mention anything about 'config+splash'.

@rsn8887 

No, this can stay open for this?
>   > I thought it was a feature here from these two lines in the readme:
>
>  Closely related but ultimately unrelated feature at the moment, but sure, could be expanded to force the splashconfig on demand also

Unless you prefer a more focused issue to close later.

**Comment by i30817** [comment]
Ok i'm going to offer a criticism that might be unwelcome so brace yourselves.

I don't think all options of whdload should be mapped and in this case this should only have 2 settings 'off' and 'on' that turns the menu on with the 'start' button whenever possible. It's simpler and vastly less confusing. And if combined with the 'button to start' idea (if possible) it means that even people that turned it off can see it if they want.

**Comment by sonninnos** [comment]
I'd also prefer WHDLoad installs to behave identically with these features, but they do not. As in actually have separate splash and config windows. Installs with configs show the configs 
when only splash is requested.

For example Midnight Resistance basic splash shows everything that the config shows (but without time to change anything, and it prechecks the custom parameters):
![retroarch_2020_03_16_20_24_26_972](https://user-images.githubusercontent.com/45124675/76789723-11eaaf80-67c6-11ea-8041-e79e0bd48207.png)

The Settlers splash only shows that configs exist, and config does nothing:
![retroarch_2020_03_16_20_25_42_768](https://user-images.githubusercontent.com/45124675/76789823-4a8a8900-67c6-11ea-8f81-3d0c7ecf9fd0.png)

Without configs 'Config + Splash' is just splash with a start-button.

And for the Amiga side controls to be in unison there would have to be a keyboard+mouse to joystick remapper. Maybe there are some, I haven't searched yet.

Because the .info selector works with cursor keys and mouse, and the MkCustom script requester only works with mouse, so it will be ugly either way if those could be controlled with the joystick port.



I'll add a third startup override button (which would be equal to config+splash) on the TODO list, and leave the core option as is, except with some label clarifying.

**Comment by i30817** [comment]
Ok, from the settlers example i see there are some installs where there are 'options' but they're not built into the menus.

But why bother showing that info in that case anyway? Wouldn't it be better that 'config' be the 'on' part  of the hypothetical dual 'on/off' whdload.prefs and simply pretend that the option the user can't change from the gui doesn't exist and skip to the game?

After all the user can't actually set it from the gui then.<

For consistency i'm actually more worried about the apparent missing 'start' button in midnight resistence. edit tested it and space/enter continues... it's probably problematic to the idea of controller only config...

**Comment by sonninnos** [comment]
> After all the user can't actually set it from the gui then.
Not immediately no, but rebooting with the spacebar down yes. I made the MkCustom script just for that reason, so that there is no need for external labor.

MkCustom is also run when WHDLoad quit-key is pressed, but since the quit-key does not always work, there had to be another method of getting there.

So you would like the override button to only do 'config', as in randomly showing something per install and making the user questioning did the override work or not..? In this case I'd rather show everything with unlimited timer.

The sublabel tells what buttons work as the start-button, so I wouldn't be too worried about start buttons being out of screen. But nothing can be done in this end about those kind of issues. That is up to the slave creators.

**Comment by i30817** [comment]
Ahh, i didn't get it that you could get a dialog to set a option after reading the readme with space by pressing esc, i just always restarted.

It doesnt work here - gnome 3 -, because i have some kind of problem with focus where there is the amiga cursor and a 'gnome' 'slide' window cursor, but that's probably a gnome3/wayland screwup and not a bug of the emulator core (retroarch maybe).

**Comment by rsn8887** [comment]
FWIW, I like seeing the splash just so I can see the game name, slave and version of the slave I am actually starting.

**Comment by i30817** [comment]
That's fair, but you can get all of that and more just by pressing space.

**Comment by sonninnos** [comment]
How about something like this, I already lurked how it can be done:
- Remove current keyboard reading (spacebar) & replace with joystick directions, like:
  - Up/Down = "Spacebar"
  - Left = Config
  - Right = Config+Splash

Pros:
- No need to have keys mapped to RetroPad

Cons:
- ?

Any objections or ideas?

**Comment by i30817** [comment]
For 'off' right? That sounds fine.

I'm thinking user will not understand the difference between 'left and right' but it doesn't matter that much because they'll only notice the inconsistency if their habits for triggering this are inconsistent, and it's subtle enough to pass unremarked.

**Comment by sonninnos** [comment]
Dammit, I hit a brick wall with the direction readings.. The only CLI program that allows reading them in the first place somehow bugs with them the first time they are read. As in just perfectly ruins using them in this kind of transparent scenario, because the button would have to be released and pressed at the right time during the first and the second read.

Like:
1. Hold a direction
2. Read joyport = none
3. Read joyport = none (...)
4. Release direction
5. Read joyport = none
6. Hold a direction
7. Read joyport = direction

And:
1. No direction held
2. Read joyport = none
3. Hold direction
4. Read joyport = direction

There is a version of the same program that does read the directions nicely, but waits endlessly until any button is pressed, so that is no good either.

Next option was to try finding a proper joystick to keyboard mapper, so then the directions could be read as keyboard presses, but couldn't find one that could be made silent and to quit cleanly after it is no longer needed.

Also I almost found a good enough joystick to mouse mapper, but can't get it work without clunky CLI messages.

So looks like the only sensible option would be to utilize the default buttons, like:
- 1/Red = Launch selector
- 2/Blue = Readme+MkCustom
- LMB = Config
- RMB = Config+Splash

Would this be satisfactory? Naturally it will override whatever the current core option setting is, not just 'off'.

**Comment by i30817** [comment]
Yeah, it would. That reading thing is not unusual, you'd have to loop with a timeout.

**Comment by sonninnos** [comment]
Well, the mouse buttons are mapped to RetroPad L2+R2 by default, so it isn't that bad, unless of course using a pad with not enough buttons.

I'm not coding anything Amiga side, just using available tools. And looks like you are in luck: This program can distinguish RED+BLUE.

And sure, that button order seems fine to me. The combined one would be the least used.

**Comment by sonninnos** [comment]
Sigh, looks like 1/Red can't be used there, because it also acts as the start-button, so one would have to be super fast to release the button once the config window appears..

**Comment by i30817** [comment]
Annoying. I'm ok with the mouse button as long as it is mapped in the retropad when using cd32 on the core. The mouse cursor starts on the top right not on top of the start button so it doesn't matter in that case.

**Comment by i30817** [comment]
Oh, i didn't read you edit. Yes, not using red for whdload works. Didn't think of it.

**Comment by sonninnos** [comment]
No issues with the combo found yet. It is only a program that outputs WARN which is read in a script, so no need to worry about frames here.
