### ISSUE TITLE
ZIP disks not mounting in .uae files

### ISSUE THREAD

**Issue by solarmon** [libretro/libretro-uae#304]
Hi,

Similar to:

https://github.com/libretro/libretro-uae/issues/278

I seem to have this issue when trying to mount ZIP disks (of ADF files) referenced in a .uae file - i.e. it doesn't mount.

This is using Retroarch 1.8.4 with  P-UAE Xtreme (June 21st 2020) core on a SNES Classic Mini.

Is this the same issue as https://github.com/libretro/libretro-uae/issues/278 ?

Thank you.

**Comment by sonninnos** [comment]
The internal ZIP handling is not working for reasons unknown (will result in crashes if enabled). ADZ (gzipped ADF) does work with that method though.

That M3U route unzips the archives in temp, just like launching ZIPs directly. UAE conf usage is discouraged anyway.

**Comment by solarmon** [comment]
@sonninnos 

Thanks for the clarification. I just wanted to make sure it was a known issue.

I'm using .uae config files because I have a tool that generates it and I would like it to be multi-platform (and multi-uae environments, not just RetroArch P-UAE).

I will try/test with GZIP, but it would be great of internal ZIP handling is fix. Is there a another separate ticket that I can follow for this issue?

Thank you.

**Comment by sonninnos** [comment]
Unfortunately using uae confs for anything else except media mounting will eventually result in having a bad time, unless one avoids using the core options page completely, since core options will have the last say, and changing one in runtime will refresh all.

Currently the conf hierarchy goes like this (check `puae_libretro.uae` under `saves` after launch):
1. core options are used as the base
2. custom .uae will be appended to the base, overriding the existing core options

Of course media rows and other options that do not exist as core options should not be a problem.

There is no other ticket, so this will do just fine in case someone wants to tackle it. This feature is not a priority for me though, sorry..

Does any UAE version handle multiple files in a single ZIP? It would be handy if M3Us and uaeconfs could understand something like `game.zip#disk.adf`.

**Comment by solarmon** [comment]
At the moment, the ZIP files I'm testing are just individually ZIP ADF files, and I'm loading them in to the floppyX drives and diskimageX for disk swaps - for example:

```
floppy0type=0
floppy0=N:\ROMs\Amiga\Games\ADF\ZIP\X\Cannon_Fodder__Disk1.zip
diskimage0=N:\ROMs\Amiga\Games\ADF\ZIP\X\Cannon_Fodder__Disk1.zip
floppy1type=0
floppy1=N:\ROMs\Amiga\Games\ADF\ZIP\X\Cannon_Fodder__Disk2.zip
diskimage1=N:\ROMs\Amiga\Games\ADF\ZIP\X\Cannon_Fodder__Disk2.zip
```

This .uae config works in WinUAE.

I was hoping it would also work in RetroArch P-UAE (on SNES Classic Mini). But it doesn't work with this equivalent .uae config:

```
floppy0type=0
floppy0=/media/ROMs/Amiga/Games/ADF/ZIP/X/Cannon_Fodder__Disk1.zip
diskimage0=/media/ROMs/Amiga/Games/ADF/ZIP/X/Cannon_Fodder__Disk1.zip
floppy1type=0
floppy1=/media/ROMs/Amiga/Games/ADF/ZIP/X/Cannon_Fodder__Disk2.zip
diskimage1=/media/ROMs/Amiga/Games/ADF/ZIP/X/Cannon_Fodder__Disk2.zip
```

I've yet to try this on Android uae4arm.

**Comment by sonninnos** [comment]
Please confirm if everything is fine after this latest change, thanks!

At least that `diskimageX` row is not needed here, but there is no harm having it. It appears to be for the UAE internal diskchanger list, which can't be used with this core anyway. Unless some kind of keyboard shortcuts are enabled for the list somehow..

**Comment by sonninnos** [comment]
All right, now these confs should finally be truly usable.
