### ISSUE TITLE
Switch latest build - errors when loading hdf's

### ISSUE THREAD

**Issue by tomjramsden** [libretro/libretro-uae#324]
Hi, 

I can't seem to load any .hdf games (latest build). I typically get a screen similar to below when attempting to load any game:

WHDloads set to hdf's and correct bioses, etc in right folder.

I have used exactly the same settings/setup on retroarch on windows_x64 build and they work absolutely fine.

![2020101910581900-F573BCCB3DAC7592845119D5A75A05AD](https://user-images.githubusercontent.com/13732780/96431092-f384e080-11fa-11eb-80b3-b306a4176051.jpg)

Thanks,

**Comment by sonninnos** [comment]
Both modes work similarly here with all hard drive content (HDF/LHA). What is wrong with having the WHDLoad mode set at default (Files)? HDF mode seriously limits savegame space and causes a lot of writes to the filesystem, because WHDLoad.hdf is modified on each run.

Both modes have identical files in them, so there should be no difference in operation. Also they haven't been changed in a long time. Is this with a clean setup, as in you let the core create all WHDLoad stuff, and not manually copied any files?

Also there is no need to hassle with HDF games anymore, because LHA games work directly. But as long as the directory structure is the same, there is no difference, because UAE sees both of them as hard drives.

And because all of that stuff is happening inside the emulation, I have no idea how the platform could cause that..

**Comment by tomjramsden** [comment]
Thanks for your reponse. I had a legacy whdload.hdf and prefs file. I cleared them. I also set the whload mode to files and tried load agony_v2.1 NTSC_2701 and got this screen....

![2020101914262500-F573BCCB3DAC7592845119D5A75A05AD](https://user-images.githubusercontent.com/13732780/96457422-a8c59180-1217-11eb-94fc-09ed015b043d.jpg)

**Comment by sonninnos** [comment]
Odd. Please provide the verbose log and the contents of `puae_libretro.uae` under `saves`.

**Comment by tomjramsden** [comment]
Here you go...
[RA_Dump.zip](https://github.com/libretro/libretro-uae/files/5402898/RA_Dump.zip)

And yes, there is a WHDLoad directory under saves with directories and files in it...

**Comment by sonninnos** [comment]
Well looks like you have enabled the "Global Boot HD" core option, which takes priority in hard drive order, so that explains that screen. That option is for installing Workbench and using floppy disks like with the real thing, not for WHDLoad usage. So disable it and all should be well then.

Also the `puae_libretro.uae` and the logfiles hint that the core version is not current, because there is no UAE output in the logs.

**Comment by tomjramsden** [comment]
Thanks @sonninnos - I switched that off but unfortunately that did't do the trick. I pulled down the latest from the core updater yesterday with a fresh install of RA.

Okay I am going to clear everything down and try and completely fresh install and let you know how I get on, thanks.

**Comment by tomjramsden** [comment]
Okay, that is even worse now - I removed all the settings, core, etc (apart from the bioises) and now retroarch crashes completely. I have attached the latest verbose logs.

Did you say it was working okay on your switch?

[RA_dump2.zip](https://github.com/libretro/libretro-uae/files/5403663/RA_dump2.zip)

**Comment by sonninnos** [comment]
I don't have one.. Also you seem to have rewind enabled. I've had some issues with it even with my setup, so please disable it. It will destroy performance massively anyway.

@rsn8887 could you take a look too?

**Comment by rsn8887** [comment]
Tested loading Barbarian.hdf from
Ransom pack on my Switch. Works just fine. Using latest core version 7bc635a.

Tried deleting retroarch config, core config, the automatically generated WHDLoad files etc. It still works.

**Comment by rsn8887** [comment]
One more thing, but you probably already know this: Make sure none of your important folders, like retroarch folder and so on, has the "archive" bit set.

**Comment by rsn8887** [comment]
It looks like this issue appeared before:
https://github.com/libretro/libretro-uae/issues/216

It was fixed by the user deleting the system/whdload files in Retroarch dir. Not sure if this helps.
