### ISSUE TITLE
WHDLoad files boot to this.

### ISSUE THREAD

**Issue by pronabol** [libretro/libretro-uae#363]
when loading games from RetroArch using WHDLoad files, this screen appears. it only appears when there are a folders in RetroArch\saves\TEMP folder which contain a sub folder called Data. Deleting the temp folder fixes this until temp reappears and starts adding game folders again. When this screen appears it makes running anymore games impossible, its happening on the PC (windows 10), on the Raspberry pi, and on the Nvidia shield, any ideas?
![New-wk](https://user-images.githubusercontent.com/76709788/103246433-51e8e080-495b-11eb-8ac6-c87652cf3463.jpg)

**Comment by sonninnos** [comment]
Whoops, there is a problem with recursion when clearing out the TEMP-dir. I'll fix it soon. I changed it recently to leave the main TEMP-dir, so that it can be used as a RAM-drive. Apparently I didn't test it with ZIPs that have directories in them.

However this whole thing will not happen when the preferred method of WHDLoad files are used, which are LHA-archives (and HDF-images).

**Comment by pronabol** [comment]
Thanks a lot, look forward to the update. I wondered why no one else had noticed, as you say most users are proberly using LHA. Again, thanks.
