### ISSUE TITLE
[Question] Resolution switching ?

### ISSUE THREAD

**Issue by WindyWinston** [libretro/libretro-uae#380]
Vaguely related to https://github.com/libretro/libretro-uae/issues/379 . WinUAE can display everything in one Hires resolution , say 720x568. Is there any way to do this in PUAE so it doesn't keep switching resolution ? (WinUAE's 'Resolution autoswitch - Disabled')

**Comment by sonninnos** [comment]
I don't understand. When does the resolution change when it is not desirable?

**Comment by WindyWinston** [comment]
It's only Demos that are a bit annoying when they switch Resolution so many times. Every time it switches the sound mutes for a fraction of a second. It's not a problem. I set the Resolution to 'High 720x' and turned off the Zoom. It still switches the Resolution between 720x288 and 720x576 though.

**Comment by sonninnos** [comment]
Sure, Line Mode toggling is on the heavy side of screen geometry altering.

I'm still on the fence which is the better default for Line Mode, Single or Auto. There are cases for Double being better for sure, but I keep it at Single first, and this case also points towards Single.

The horizontal Auto is indeed mostly useless and harmless, since only Super Skidmarks needs Super-Hires, but at least Workbench behaves well.
