### ISSUE TITLE
[Xbox S Series] Unable to change Game Disks PUAE core 2.6.1 (9860677)

### ISSUE THREAD

**Issue by foxhidden2009** [libretro/libretro-uae#406]
Hello !

I am currently having a problem on RetroArch 1.9.1, PUAE core 2.6.1 (9860677) with *.adf multi discs.

When the game told me to change Disk and insert the Disk 2 for example, I'm unable to load it.

I have tested with 3 games and have reset the core config to be sure, but no way. I have tried to Eject Disc, return to the game, go The "Disc Control" and then load it's not working. Game is not freezing, just not loading when I press "Fire".

I have tried to create a *.m3u files with the name of the 2 disks but when I go to "Disc Control" -> "Load New Disc" Only Disc One is displayed... I have read somewhere that *.m3u is not supported on Xbox ...

I have tested on my PC with the RetroArch build x64 1.9.1 PUAE (2.6.1 b0c3cd4) and I can load Disk 2 with same games without problems.

So I wondering if it's an issue with the version of the core on xbox ?

If so, do you have any tips or a workaround to load disks ? It's a little frustrating because your emulator is running very well otherwise and it's so a pleasure to play games we own as kid :)

Thanks for your help !

**Comment by sonninnos** [comment]
Cheers. There is no need to return to the emulation after insert/eject in this core, since there is a delay in the insertion. Thanks to at least one game (Flashback), that will not notice that the disk has changed unless the drive is empty for a moment.

Everything is working on my end (M3U launch and via Disc Control), and since I don't have an Xbox, all I can work with is the verbose log. And with debug level log there will be output of the paths in the M3U file. I have no idea what else might or could be wrong.

Try putting all the ADFs in a single ZIP and launch that. It will/should extract and create a M3U file automatically. There is no real reason to append disks with "Load New Disc" when using M3U files, but simply change the index when required. As in if the game does not support external drives (which are enabled by default), or has more disks than there are external drives.

And of course WHDLoad LHAs won't have any hassle with disks.

**Comment by sonninnos** [comment]
Please test if any recent change helped anything.
