### ISSUE TITLE
Using MegaAGS in lr-puae tutorial

### ISSUE THREAD

**Issue by fzacchi** [libretro/libretro-uae#415]
I'm trying to use the latest Amiga MegaAGS collection with lr-puae on Retropie with the Raspberry Pi 3B+.

It's a giant 6GB .hdf image with everything included, it should be just possible to boot from it.

I tried 
hardfile=read-write,32,1,2,512,"/home/pi/RetroPie/roms/amiga/BootHD/MegaAGS.hdf"

in puae_libretro.uae, with no success.

Any help? Thanks.

**Comment by sonninnos** [comment]
Someone would need to backport >2GB support first.

HDFs are not recommended at any size anyway, because savestates/rewind will eventually corrupt them.

**Comment by sonninnos** [comment]
Current version should be able to handle yuge files without any config tinkering.

Besides editing `puae_libretro.uae` does nothing since it is always overwritten at launch, or rather was, since the file is not used anymore. Also it appears that HDFs bigger than 1GB need `32,16,2,512` instead, which is now automatic, as is RDB detection, which is `0,0,0,512`.

**Comment by sonninnos** [comment]
I'll close this, because it should work, but let's open it if you still have problems and/or need manual .uae conf action for opening the image.
