### ISSUE TITLE
Not building for OSX

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-uae#45]
The nightly buildbot versions don't appear to include the latest changes

**Comment by DamsRoxxx** [comment]
When I fixed the build for Windows in PR #30 I broke other platforms like linux (Did not see it because there was a bug in Travis which built the master not the PR at the time).

I've fixed this in PR #34 but this PR still waiting to be merged (tested it on a private linux box).

Maybe it should fix OSX too...

**Comment by DamsRoxxx** [comment]
Hi @zach-morris,

#34 was merged and the nightly buildbot version seems to have been updated.

Could you give it a try and see if everything is working ?

**Comment by zach-morris** [comment]
Works like a charm now, and it's very helpful to have the git version reported, thanks for that!
