### ISSUE TITLE
I need help with P-UAE

### ISSUE THREAD

**Issue by CommodoreOS** [libretro/libretro-uae#462]
I have compiled RetroArch 1.7.0 on a Mini Console, THEC64 Mini/Maxi/Vic20, A20,H3 SoC, they only have 256 memory, P-UAE Core works but it can not load a lha ,adf or hdf without using a .uae file, if you try to load a adf file from the RA menu  on it own RA crashes, what I need to know is where do I put `puae_libretro_global.uae` in a older version, do I still put it in the saves folder...?

It happens to UAE4Arm Core as well, they both are acting the same, but that will not load hdf hard drive files from a uae file.
I did compile RA 1.9.6 but P-UAE core dose not load and says `cannot map zero-fill pages` so I am guessing thats a memory problem..?

**Comment by sonninnos** [comment]
This is not a help desk, and it is very likely that those problems can't be fixed by changing the code here, since it also affects some other core..

There is zero reason to hassle with `.uae` files anymore. All different file formats create a launch conf accordingly. What are you even trying to accomplish with the global conf? Of course the location has always been the same.

Verbose log will show what is happening. Also the generated conf will be there when log level is set to debug (Previously it was written to a file).

**Comment by CommodoreOS** [comment]
Sorry for asking here, there is not a lot of info or old info on P-UAE, never heard of it before, I try it cause it came with RA 1.7.0, (its P-UAE 2.6.1) I only got it working cause of UAE4Arm, I was trying to to get that to work with a hdf file and it would not load it so I tried in P-UAE and it loaded it,it has the same problem, it does not run a game without a .uae file, I used WinUAE to make the .uae files, a older version WinUAE 2.8.1, WinUAE is the best emulator out there for the Amiga been using WinUAE from its beginning and in Amiga Forever, P-UAE will not run WHDLoad games but thats properly cause it not supported, anyway thanks for replying.. :) Sometime it better getting a answer from someone involved in the project or from the horses mouth... :)
