### ISSUE TITLE
Super Street Fighter II HDF not working

### ISSUE THREAD

**Issue by ToniBC** [libretro/libretro-uae#464]
Hi, I'm trying to play this game, but I can't. I am with Retroarch nightly, core updated under Windows 10 x64.

The game Super Street Fighter II in its .ADF version works, but in its HDF version it does not load, it is left with a black screen.
I have all the kickstarts as well.

Other versions like Super Street Fighter II Turbo, if they load and the Street Fighter II, I only have the problem with the Super Street Fighter II.

I also tried a compilation in HDF of all the Street Fighters and they all load except the normal Super or AGA that always gives a black screen.

I have the cycle precision, I have modified several options and Amiga models, but nothing.

I see that it worked before, but now it seems that it doesn't.

Can someone check if it works and what options to put in case it works.

Thanks.

**Comment by sonninnos** [comment]
WHDLoad versions do not work for some reason, but regular HD installable does fine with defaults:

![retroarch_2021_11_03_10_04_23_279](https://user-images.githubusercontent.com/45124675/140027244-1a171226-a0a7-4a85-945c-de6874f21065.png)

**Comment by ToniBC** [comment]
Here I am a little lost. There is a tutorial or video where I explained how to create an installable version of a game or how to install a game using the core, because the only thing I found are the adf and hdf versions.

I do not know if the installable version will be with another extension or can be played without having to change discs.

It is that the Friend I never had and I am somewhat lost.

**Comment by sonninnos** [comment]
Well if the HDF version does not work, it must be the WHDLoad version and not the actual HD installed version. The first disk has the installer, which obviously has to be run from Workbench, as in not booted from. It can be done easily with the core by using the "Global Boot HD" core option (After installing Workbench to it of course).

The installer is rather dumb, because it wants to create a blank boot disk, which is also easy to do with the core (SVDS key in VKBD), and the boot disk only has `Startup-Sequence` which can be simply copied to create a single bootable HDF.

**Comment by i30817** [comment]
Speaking of street fighter 2, the super-turbo versions have a weird behavior with controls where you can move in directions without game focus on, and can throw punches and kicks _with_ game focus on, but not both.

Probably a whdload mistake, but just so you know.

**Comment by sonninnos** [comment]
Even the AGA version of SSF2Turbo seems to be requiring a CD32 pad, which makes sense since one regular fire button joystick, or even two button joystick simply is not enough in this case. Weird that menu can be triggered with a regular joystick though, but not player selection.

The mappings exist in core options because with these Commodore computers it is a very common requirement to mix joystick buttons and keyboard keys, because single fire joysticks were mostly used. 

It is way better to create a fantasy joypad in emulation instead of reaching out for the spacebar whenever it is required for jumping etc, and for cases where a physical keyboard is not available. CD32 pad type will override all those core option mappings when they overlap.

Game focus has nothing to do with controllers, only keyboard. In this game player 1 can be controlled with the keyboard using numpad, but looks like player 2 only has fire buttons on the keyboard, but not movement..

And no, there is no way to change the controller type default depending on content, since it is dictated by the frontend. Sure would be nice to be able to do it for CD32 games.

**Comment by i30817** [comment]
I wish there was a way to move the 'cd32' to the core so the core could auto configure based on name ie: 'CD32' in the name, because doing this per-game is annoying.

**Comment by sonninnos** [comment]
Then again using those WHDLoad CD32 versions is not that wise anyway, since they will be missing CD audio if there are any. With actual CD images one can simply do a content dir remap and be done with it.

RetroPad would be unusable without keyboard key bonuses, but a CD32 controller does not require any, because CD32 does not have a keyboard by default. It has to be a separate selectable option, because sometimes you might want a CD32 pad with non-CD32 games, and sometimes wou want a Mouse+Keyboard combo with CD32 games. If it would only be in core options, it would be even more messier.

**Comment by i30817** [comment]
> The mappings exist in core options because with these Commodore computers it is a very common requirement to mix joystick buttons and keyboard keys, because single fire joysticks were mostly used.

BTW, i just found out you _can't_ save as a core option Input-type to CD32 Pad. (The only 'retropad' string in ~/.config/retroarch/config/PUAE/PUAE.opt after changing to that and saving core options is `puae_retropad_options = "disabled"` and if you restart the game it says the configuration override was loaded but if you go back to input it's back to retropad.


So... what can be done to resolve this in the best way possible? I was trying to set all amiga to try to load with a cd32 pad since they're not _that_ different from a retropad and seem to have better results on a wide range of whdload games (for some reason, i suppose i was naive to think that they would work the same). What now?

**Comment by sonninnos** [comment]
No, there is no core option for the device type, changing it is only possible via the frontend remap controls. Simply save the remap per core/directory/game under Quick Menu > Controls and don't use Settings > Input.

Sure, a widening bunch of WHDLoad installs have added support for CD32 controller and/or second fire button, but I don't think they are enabled by default that often.

It does not matter what device is used as a controller, since it is seen as the controller, not the device.

**Comment by i30817** [comment]
Thanks, can't believe i missed it.
