### ISSUE TITLE
Changing cpu compatibility during gameplay!!

### ISSUE THREAD

**Issue by bigly2001** [libretro/libretro-uae#465]
Hi
As you know playing games in "cpu compatibility: cycle exact" on Tinkerboard and etc ... is imposible because of lack of speed. 
for example to play **First Samurai** you need to set cpu compatibility to cycle exact  in order to play. the game run perfectly but with 8-10 fps and it doesnt playable.
In past with older build of puae i did a workaround to play such games like First Samurai or Aladdin.
I did run puae with Cycle exact and load First Samurai Disk 1. when i saw the first screen of  game (Vivid image screen) then 
got to menu and change cpu compatibility to normal and resume the game . that change must be set in first screen and so quick. if you do it with delay the amiga will reset and  guru meditation etc..
with this workaround game ran perfectly with full frame i think because cycle exact was needed to run only for intro of this games.

But on latest bulid of puae when you change cpu compatibility during the gameplay it was not applied.
retroarch was shown cpu compatibility was changed. but in real not applied.

Would you please let to change cpu compatibility during emulation like past.
I know in real world its not imposible but in emulation you can do everything everything.

thanks in advance
bigly

**Comment by sonninnos** [comment]
Nothing has been changed regarding that and it works fine here, but some games freeze, and always have, when doing it realtime.

**Comment by bigly2001** [comment]
Hi
I tried many times and it did not work like past.
for example I  loaded  a game like first samurai with cycle exact configuration  and when the game starts. it is too slow.  now change cpu configuration to normal and resume it but the game still is  too slow . 
 while it must be run perfectly with full frame.
I did this tricks many times in past because first samurai is my favorith game

thanks in advance
bigly

**Comment by sonninnos** [comment]
Yes I heard that the first time, and it is still not helpful, especially since the option changes here in realtime just like it has for a long time.

I have no idea what could be the cause since it simply cannot be the libretro side of updating the setting, and there has been no changes in libretro side or the actual UAE side either.

For example here my fastforward speed is about ~300fps in First Samurai with Cycle-exact, and when I put it back to Normal, fastforward speed is about ~600fps, so it clearly does something and also the game works.
