### ISSUE TITLE
Probably doing something wrong - worms director's cut whdload

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-uae#466]
These whdloads have memory requirements in the name of the filename (in the retroplay set), ie, 8 mb, 12mb etc, and 'AGA' as well as '0605' whatever that is. I suppose a Amiga 1200.

Thus i was surprised that when booting it said it couldn't allocate ExpMem (both versions but i tried it mostly on the 8mb one since the '12mb' didn't seem to match any of the available models in the listing.

Speaking off the listing, when i tried to force A1200 8mb instead of automatic, it failed in the same way and i think that was the exact same model that automatic was choosing for AGA. I tried the others but it didn't help.

So...

**Comment by sonninnos** [comment]
Getting more than 2MB chip + 8MB fast is not currently possible, because that requires JIT. Automatic will pick the 10MB maximum combined memory, which is shown in the statusbar.

Readme says:
```
It requires:
- 2 MB ChipMem and 2 MB OtherMem
```
And:
```
- Some slaves added, more RAM used (you can include more gfx/sound customs)
```

The game data is barely over 2MB unpacked, and that version without the memory number works fine. Also there is no way to add any custom data to LHA archives, so they would need to be extracted to files or converted to HDF. And still the custom data can be used with the basic slave, but it won't all fit in memory at once, and actually filling those allowed amounts with custom data is very unlikely.

Which means this issue can be closed, since the payoff versus effort is not reasonable.

That "0605" is the SPS game id listed at http://www.softpres.org/games
