### ISSUE TITLE
(Enhancement request) Add a joystick-mouse switch status

### ISSUE THREAD

**Issue by iconoclusterdotexe** [libretro/libretro-uae#507]
I really love PUAE core, but i want to suggest a useful function that maybe can be implemented: Add a one second timed joystick-mouse switch status without enabling the OSD statusbar mode. Just an icon or a comment saying "Mouse mode" or "Joystick mode".
Maybe a similar function is can be useful for Vice core for Port 1 and 2 switching. @sonninnos what do you think about of this?

**Comment by iconoclusterdotexe** [comment]
For example, I've made some icons where you can use for that implementation (sorry for the phone camera shot, but i don't want to show them as a regular image atm.)

![IMG_20220402_180736.jpg](https://user-images.githubusercontent.com/75033413/161391495-1067bf5d-b741-4358-907b-8c4085bbb01d.jpg)

**Comment by sonninnos** [comment]
It would require a new statusbar mode which forcefully shows itself on those special occasions, and while I'm not a huge fan, I guess I could take look at what it takes. VICE already has a statusbar notification for that toggle, but I decided it was enough in PUAE to just change the port letter without an extra message.

Perhaps the frontend widget could be used instead, since those also can be hidden. Total immersion core-wise is a requirement though as the default.

**Comment by iconoclusterdotexe** [comment]
That's true, but maybe an option to enable or disable the function. I think a small written notify would be sufficient.

**Comment by sonninnos** [comment]
Okeydokey this is where I'm at now:

![retroarch_2022_04_03_17_02_19_738](https://user-images.githubusercontent.com/45124675/161431734-49b89d19-bb7c-4ef8-8668-c1c58de88bd2.png)

![retroarch_2022_04_03_17_04_42_466](https://user-images.githubusercontent.com/45124675/161431812-3e2e5e81-97ca-440d-a377-1c89a45dd5da.png)

![retroarch_2022_04_03_17_04_44_300](https://user-images.githubusercontent.com/45124675/161431818-1ac922d8-3974-476d-86cf-23ad13bc00f4.png)

**Comment by iconoclusterdotexe** [comment]
Absolutely perfect! ❤️

**Comment by sonninnos** [comment]
Cool, thanks! I'll add it to VICE and old PUAE too after more testing and polishing.
