### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by Gogerad** [libretro/libretro-uae#514]
Hello to the community,

![téléchargement](https://user-images.githubusercontent.com/77921371/162643982-4d83711b-d7d9-41c0-b9b5-14c21bdfeff9.png)

Can someone explain to me why when i try to start some ipf roms, i got this message ?
I try several things without success.

Any help would be appreciate :)

**Comment by sonninnos** [comment]
https://github.com/libretro/libretro-uae#ipf-support

**Comment by Gogerad** [comment]
Thanks for the link.
I was aware of the capsimg.dll file to put in retroarch folder.

Most of my ipf files work but some of them give me this screen like Star Trek.
Besides, i got a few roms running too fast.

**Comment by sonninnos** [comment]
Both have nothing to do with this core particularly, but Amiga and Amiga emulation in general.

Star Trek is not playable from disks:
```
- Game is playable from HD only.
- HD installer is contained on disk 1.
- Installation requires approx. 9Mb HD space.
```

And there are multiple options to slow down the emulated hardware. Sometimes it is enough to use the CPU speed option, sometimes you need Cycle-exact. 

And sorry, but this is not a help desk. This is for things that can be fixed in code, thus I'm closing this.
