### ISSUE TITLE
[RPI4] Very short screen and sound freeze with auto zoom mode.

### ISSUE THREAD

**Issue by iconoclusterdotexe** [libretro/libretro-uae#522]
Platform: RPi4 8GB
Retroarch version: 1.10.3
PUAE and PUAE2021 cores version: latest (with last commit)
Running on Batocera (a customized version, with original flags on compiling)

I've noticed a very short screen and sound freeze when using the Automatic Zoom Mode. This happens when it cut vertically the overscan and extends the image screen to the monitor-tv frame (on vertical obv).

You can reproduce the issue by using every RA Aspect Ratio,  Zoom Mode = Automatic and Zoom Mode Crop = every (except horizontal).

It's not a big issue, but it's quite annoying.

**Comment by sonninnos** [comment]
I'm pretty sure the geometry resizing can't be made any faster. Try increasing frontend sound latency.

**Comment by sonninnos** [comment]
What game is that, since changing the screen size so often is no bueno?

**Comment by sonninnos** [comment]
I've been using Automatic ever since I created it, and the impact is minimal with my hardware. I doubt that is going to change ever, but I'll try to optimize it to skip that kind of small change.

As in it is not the Automatic per se but the change in general. Same can be observed with manual zoom toggling.

**Comment by sonninnos** [comment]
Good. Pointless screen size changing is also sorted and will be in the next update.
