### ISSUE TITLE
Hard Drivin' option screen (WHDLoad)

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#548]
Just wondered if anyone has got the option screen to work on the WHDLoad version of Hard Drivin' ? It says 'press O for options' but it doesn't do anything. I can't find anything about it on the net so wondered if anyone knew how. The floppy version works.

**Comment by i30817** [comment]
Try the controller buttons if you have it and reading the documentation when booting (it's a button combination i forget)

WHDLoads have the habit of changing games so they can be controlled by the controller. So adventure games for example, select options from cycling the selection with buttons instead of displaying all of them and clicking etc.

It's awkward because sometimes the game screens say one thing and you need to do something else.

**Comment by sonninnos** [comment]
Same thing happens in WinUAE, so there is nothing to be done here. Clearly the slave is to blame, so I'll close this.

The Readme says nothing particular regarding input, except:
```
Q       = abort the current race
```
But even that does not work. So perhaps all game keyboard input is goofed somewhow. Then again Q does nothing in the floppy version either, but there O works even during "gameplay". Not a huge loss if you can't select the controlling method, since it is dog shit no matter what.
