### ISSUE TITLE
IPF save support

### ISSUE THREAD

**Issue by vagrant-17** [libretro/libretro-uae#550]
Looks like IPF saving is not supported, unless I overlooked something.
Is it possible to add write support via files like winuae does?

**Comment by sonninnos** [comment]
No. Nothing writes to IPFs. This uses the exact same code that WinUAE does.

**Comment by sonninnos** [comment]
A save disk creation feature already exists in the core (which is enough for the majority of games since they use a separate save disk, but can't work when the game wants to write on the main disk), and the WinUAE disk replace feature is dodgy at best. Totally not worth it adding it here.

Why not just use WHDLoads?

**Comment by vagrant-17** [comment]
DOS format disk easiest workaround is just copy the ipf to an adf.
No idea why giana sisters would crash but I've never had problems with ipf saving on winuae.
There are many non-dos amiga games without a whd install that expect writing to the game disk.
Also for users that want to use original floppy images instead of whdload cannot save there scores in Pinball Dreams for example (or every other ndos game).. unless using a cracked adf.

**Comment by vagrant-17** [comment]
I think would definitely be a worthy addition if possible mate

**Comment by sonninnos** [comment]
Still seems like a massive waste of time, since there really aren't that many of those kind of savings, but fine, whatever.

**Comment by sonninnos** [comment]
I was able to make this happen with fairly small effort. I decided to add a new core option for setting the disk drive unit which has the disk that should be redirected. Seems to work fine with Pinball Dreams, which needs to be using DF1: for the disk if MultiDrive is enabled, since it saves to disk 2.

Obviously it can't be enabled all the time and not for all drives, since it would create a lot of unnecessary files under `saves`.

Not sure if I should try to make sure that the save disk won't be used if the core option is disabled, since the UAE internal feature will scan for the existence of the file regardless as is..

And maybe the created disk should be compressed on quit and extracted on start, since the file will be 2MB in size, yet has only a few kilobytes of data.

**Comment by vagrant-17** [comment]
Ok thats great soninnos, sounds good :)

I went through a lot of IPF images some months ago, only games that have no WHD install.
There were some non-dos games that refused to save data of course, but there were also games that refused to run at all unless the game disk is write-enabled!
This usually result in neverending write-enable requests.. I don't remember which games though, probably should have written them down.

**Comment by sonninnos** [comment]
I was able to simplify it further as a simple toggle option which affects all disk drives, since UAE already deletes disks that are not written to. And I also added compression to these save disks, and also to the previously available manual save disks.

**Comment by vagrant-17** [comment]
Excellent! Thanks sonninos 👍
