### ISSUE TITLE
PUAE dose not Support Zorro III Ram

### ISSUE THREAD

**Issue by CommodoreOS** [libretro/libretro-uae#552]
I tried this in RA 1.7.0 and RA 1.10.3 and its not working, can not get extra ram, only can change the Chipram and Fastram.
It acting like the Zorro III graphics card is not supported when it was in E-UAE, this is E-UAE and WinUAE, P stands for Port so should be able to use E-UAE settings inside a .uae file.
`z3mem_size=32`
and get this below...
`Unsupported graphics card memory size 2000000 (0)!`
`gfxcard_size=32`
and get this below...
`Unsupported Zorro III fastmem size 2000000 (0)!`

**Comment by sonninnos** [comment]
But there is a core option for it and it is working fine here.

Picasso is not supported, so `gfxcard_size` can't do anything, and `z3mem_size` works as long as `cpu_24bit_addressing=false` is also set.

RA version does not matter, only PUAE version matters as long as it is after this commit https://github.com/libretro/libretro-uae/commit/1aa0910629dea3c3e0d28552155613ac8dd19c2d if using the old `2.6.1` branch, since it was forcefully disabled in it.
