### ISSUE TITLE
PUAE 50hz

### ISSUE THREAD

**Issue by AxelFoley68** [libretro/libretro-uae#566]
Puae is really nice under retroarch. :-)
Is it possible to get vsync 50hz like winuae ?
Or am I missing something

**Comment by sonninnos** [comment]
Yes you are missing something. The core does not decide vsync, frontend does. Rate switch already happens automatically on Windows when using non-windowed fullscreen if the display exposes 50hz, but other platforms currently require manual refresh rate forcing on startup, and can't enjoy dynamic switching while running.

So if running 50hz content on 60hz display rate the frontend will disable vsync, which is the default position since windowed fullscreen is the default.

Core can't do anything about it except offer the proper rate, which it already does, thus there is nothing to be done here, so you should rather ask in forums how to do rate switching if you can't figure it out.

**Comment by AxelFoley68** [comment]
Check, thanks.

**Comment by sonninnos** [comment]
I'll close this then since the core is doing everything correctly.
