### ISSUE TITLE
Keyboard-Input: Key "s" creates input event "s " (with a space) and prevents e.g. "bmx simulator" to start

### ISSUE THREAD

**Issue by hoderer** [libretro/libretro-uae#587]
This happens with PUAE and PUAE 2021 cores. Can anyone reproduce this or did I mess up retroarch (wouldn't be the first time...)?

I use the WHDload version of the game and have to use the older PUAE 2021-core, I get an error with latest core.

Thanks for your great work and for looking into this.

EDIT: As a workaround I use the onscreen-keyboard, which works the way it should.

**Comment by sonninnos** [comment]
No. By default keyboard S is RetroPad X, which presses Space. So either toggle Game Focus (default Scroll Lock) to type keyboard keys, or unbind the keyboard RetroPad mappings from the frontend. Or change the mapping in the core to press S instead of Space.

This is not a core issue, but a frontend necessity when managing keyboards with computers that also use a keyboard.

Also I don't get duplicate inputs, but only Space, when X is mapped to it. Also I don't get any errors with  the current core version.

**Comment by sonninnos** [comment]
It is not "messed" since it is by default that way to prevent double inputs.

**Comment by hoderer** [comment]
No, don't get me wrong. I meant I messed it up, not that it's messed up by default... :)

**Comment by sonninnos** [comment]
I'll close this since there is nothing to be done by changing the code here.
