### ISSUE TITLE
Fails to load files if save directory contains accented characters

### ISSUE THREAD

**Issue by GitGub58** [libretro/libretro-uae#589]
Overriding the savefile directory in the retroarch.cfg file with a directory path with accented files causes games to fail loading.

Example:
savefile_directory = ":\sáves"

Same for absolute paths, like 
savefile_directory = "F:\sáves"

Shows the amiga error screen with the message "No disk present in device WHDLoad".

Renaming the directory makes the game load work normally.

**Comment by sonninnos** [comment]
This is a bit more complicated than anticipated, since I keep getting new curve balls once I sort some out..

Most of it works now, but some random files are not being read properly if the path has non-ascii chars.

Such as if launching LHAs (accessed directly) everything else seems to work except the loading of `WHDLoad.prefs` file which does exist just like every other file in the helper image. And if launching ZIPs (exctracts to TEMP which is under `saves`) it won't even accept the path as a drive. Does not compute at all, but I'll keep trying.
