### ISSUE TITLE
WHDLoad Generic Games

### ISSUE THREAD

**Issue by zzedmore** [libretro/libretro-uae#602]
Hi, there are a lot of these WHDLG installs on the net by a user named Aladin. Basically stuff that hasn't got an official LHA, mostly PD. You probably already know this. I have a couple of questions/issues.

A lot of them come up with the requester asking to choose one of the .info files. I normally choose 'Workbench31 4 MB.info'. Is there any way to add this to the MkCustom so that it automatically chooses the stated file ? I tried typing '`slave=workbench31_4.slave`'  into MkCustom but it isn't recognized, 'wrong number of arguments' or something ?

When loading the attached game (not really a demo, just shareware) it says that 'xpkBLZW.library' is required. Any chance you could officially add this to the WHDLoad files ?

Thanks 😃 

[BacmanAGAdemo-WHDL.zip](https://github.com/libretro/libretro-uae/files/11239861/BacmanAGAdemo-WHDL.zip)

**Comment by sonninnos** [comment]
Hmm. MkCustom value is passed to WHDLoad command as a bonus after already determining what the slave is. The script would need a serious rewrite to work with packages that have multiple slaves..

Adding the compressor should be easily doable, as long as I can find it, since it wasn't in this xpk package from aminet: https://aminet.net/package/util/pack/xpk_User

**Comment by zzedmore** [comment]
It wasn't in my ClassicWB either but I just looked and it seems it's in the LHA I posted above !

**Comment by sonninnos** [comment]
Because it isn't in the boot/sys drive path, which is the WHDLoad helper image.

**Comment by rsn8887** [comment]
By the way, the little tool kgiconload allows you to launch a .info file directly from the commandline, so it helps to launch WHDLoad games where the .info has a different name than the .slave. It launches with all tool type options as well!

kgiconload link:
http://eab.abime.net/showpost.php?p=584390&postcount=72

**Comment by sonninnos** [comment]
`WBRun` does that already. The issue is which info should get picked when there are many. Sometimes alphabetical first might be correct, sometimes not.

If that allows adding tooltype parameters to the info on the fly then it will an improvement. `WBRun` does not seem to be able to, and thus info is not used when using custom tooltypes.

Not sure why this was closed since I was planning to add support for these special installs so that it picks the 4MB slave if one exists, since that is the most reasonable one. And if it won't work, the fire button can still be held down to bring up the requester.

**Comment by rsn8887** [comment]
WBrun launches a program using the .info information, as if run in WB.

kgiconload launches a .info as if you double clicked it on the Workbench.

I remember there’s an important difference between kgiconload and wbrun when loading the generic WHDLoad games with correct tool types from correct .info.

**Comment by rsn8887** [comment]
You are right, WBRun works just like kgiconload, but you have to run it like this:
WBrun blahblah
to start blahblah.info
For comparison, kgiconload needs this:
kgiconload blahblah.info

**Comment by sonninnos** [comment]
Indeed not needing to remove the extension would make the script somewhat simpler, but oh well, what is done is done.

I managed to make this particular Bacman game to start now properly without any trickery by modifying the script and by adding the missing library. Any other problem cases I should be aware of while I'm at it?

**Comment by zzedmore** [comment]
I just tried 'SpaceTaxi3-WHDL.lha' and 'GianaSistersSE_v1.2.lha'. They already boot straight into the game with the current version of PUAE. Are you using different versions ?

**Comment by sonninnos** [comment]
Different versions. Giana Sisters SE is straight from pixelglass.org, and this Space Taxi 3 is just `spacetaxi3.lha` as in not a WHDLoad version.
