### ISSUE TITLE
Wrong boot disk selected for zipped IPF by scanner

### ISSUE THREAD

**Issue by fallenguru** [libretro/libretro-uae#626]
The no-intro set has IPF files, all disks for one game in a single ZIP.

They are recognised by Retroarch's automatic scanner. However, launching such a game (via the resulting playlist entry) will fail, because for some reason the playlist will have the wrong disk (and, AFAICT, only one disk).

Take, for example, 
`40a5ddb414b2f1e943a68f1f0c82e16d *It Came from the Desert (Europe).zip`, contents:
```
It Came from the Desert (Europe) (Disk 1).ipf
It Came from the Desert (Europe) (Disk 2).ipf
It Came from the Desert (Europe) (Disk 3).ipf
```

The scanner will select "Disk 3", which obviously won't boot, so all you get is the hand holding up the workbench disk. (And trying to change the disk via the Quick Menu will crash Retroarch.)

Now, launching the same game and file via Load Content works fine; don't even need to swap disks.

**Comment by sonninnos** [comment]
Nothing to do with the core but the scanner and the database which has the wrong thing to match as the entry. 

This core wants the whole zip as content and not any files inside it. So either use manual scan or delete all stuff after `#` and the sign itself in all paths so that the archive is the content.

So this can't be fixed by doing anything with the core. It is a database + frontend issue, so I will close this.

Also using the WHDLoad set is a much better choice in every possible way.

**Comment by fallenguru** [comment]
Fair enough, what would be the appropriate place to report this?

**Comment by sonninnos** [comment]
Already did it before your issue: https://github.com/libretro/libretro-database/issues/1387
