### ISSUE TITLE
ASPR stuck to NTSC

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-uae#636]
Hi,
I used to be able to easily swith between PAL and NTSC aspect ratios using the ASPR virtual key next to STBR, but now it seems stuck to NTSC, no matter what my video settings are. Did u overlook something?

Many thanks and best regards

**Comment by sonninnos** [comment]
Whoops, good catch. The type of the integer was changed, but not on the one referencing the variable as extern. Fix incoming ASAP.

**Comment by Vweber73** [comment]
Many thanks!

**Comment by Vweber73** [comment]
I could download the new core and now I can switch ok, thanks!
Only thing. When CROP mode is on (full screen), swichting to NTSC ratio cuts the screen horizontally on top. Also, in CROP mode the status bar overlaps the Amiga screen instead of being below. 
I tried this on F/A 18 interceptor. Is it supposed to be that way?

**Comment by sonninnos** [comment]
I have no idea what you mean. FA18 behaves just as expected (as in centered) in every crop mode and pixel aspect ratio, since it does not use full PAL resolution. I see no weirdness in statusbar location either in any mode.

PAL resolutions (256+) will not work properly in NTSC aspect mode, since it will also use the NTSC resolution so that it looks like it is in real NTSC mode without changing speed, which can't fit full PAL height.

**Comment by Vweber73** [comment]
What I mean is this:
![Screenshot_20231014_220326_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/7df57d0b-0d64-4169-8346-18d2ecf7998e)
![Screenshot_20231014_220315_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/1ae77931-7596-4a85-a7e6-1f1ae92c76c2)

![Screenshot_20231014_220315_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/162357bb-3ca7-42a1-8959-a4ff67e3a5b4)

**Comment by Vweber73** [comment]
I think that's because I used "automatic PAL". Switching to "automatic NTSC" fixes it.

**Comment by Vweber73** [comment]
I also have this overlap for the status bar 
![Screenshot_20231014_224542_RetroArch (AArch64)](https://github.com/libretro/libretro-uae/assets/92450215/01ba5be5-8e38-4d82-bf2a-68e4898d6a4c)

**Comment by sonninnos** [comment]
I tried the WHDLoad version which goes straight to the game instead of that Workbench screen, so there is no such issues there.

Clearly the screen is using 256 height for some reason even if it looks empty, therefore it can't fit the NTSC size, as I described. Running in real NTSC of course never can go over 240 height.

Statusbar is never below the image, but inside the image, so it is correct.

**Comment by Vweber73** [comment]
Ok, thanks!
