### ISSUE TITLE
Simultaneous key presses can cancel each other out.

### ISSUE THREAD

**Issue by modeler** [libretro/libretro-uae#9]
When using keyboard input (standard RetroPad configuration) to emulate the joystick, quick movements e.g. left / right can cancel each other altogether. If for example the left and right arrow keys are held simultaneously for a split second during frantic gameplay, the core appears to stop reading input until both keys are released. Physical controllers with a D-pad work perfectly since it is impossible to accidentally press left and right at the same time.

I don't know of any other libretro core that suffers from this. FS-UAE doesn't have this problem either, but I cannot test stand-alone P-UAE at the moment as I'm having issues getting it to build. I will update this issue when I have a yes / no answer on that.

**Comment by Galious** [comment]
After almost 3 years, the issue is still present, preventing proper keyboard use in games.

Test environment:
Windows 10 x64, Retroarch 1.7.5, core: PUAE 2.6.1 a739e45, media: Rick_Dangerous.adf

Here are some pictures comparing P-UAE core and FS-UAE behaviors.

![test1](https://user-images.githubusercontent.com/22257908/52809210-02afa480-3090-11e9-9f36-47aee41f6fa1.png)

![test2](https://user-images.githubusercontent.com/22257908/52809046-a9477580-308f-11e9-8a4d-46c4969b380b.png)
